/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package markdowneditor.ui;

import java.awt.Dimension;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import org.commonmark.ext.gfm.tables.TablesExtension;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;
import java.util.Arrays;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import markdowneditor.controller.EditorController;
import markdowneditor.controller.PreviewController;
import markdowneditor.model.DocumentModel;
import org.commonmark.Extension;

/**
 *
 * @author Aung Thu Hein
 */
public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    private final DocumentModel model = new DocumentModel();
    private EditorController editorController;
    private PreviewController previewController;
    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {

        installFlatLaf();
        initComponents();
        
        editorController = new EditorController(this, txtEditor, model);
        previewController = new PreviewController(previewPane, txtEditor);
        
        txtEditor.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { onEdit(); }
            public void removeUpdate(DocumentEvent e) { onEdit(); }
            public void changedUpdate(DocumentEvent e) { onEdit(); }
        });
    }

    private void onEdit(){
        previewController.updatePreview();
        model.setModified(true);
    }
    
    private static void installFlatLaf() {
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
        } catch (Exception e) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception ignored) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Outer = new javax.swing.JSplitPane();
        Side = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtEditor = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        previewPane = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuSaveAs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Side.setMinimumSize(new java.awt.Dimension(60, 16));
        Side.setViewportView(jTree1);

        Outer.setLeftComponent(Side);

        txtEditor.setColumns(20);
        txtEditor.setRows(5);
        jScrollPane3.setViewportView(txtEditor);

        jSplitPane1.setLeftComponent(jScrollPane3);

        previewPane.setContentType("text/html"); // NOI18N
        jScrollPane4.setViewportView(previewPane);

        jSplitPane1.setRightComponent(jScrollPane4);

        Outer.setRightComponent(jSplitPane1);

        getContentPane().add(Outer, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuOpen.setText("Open");
        menuOpen.addActionListener(this::menuOpenActionPerformed);
        jMenu1.add(menuOpen);

        menuSave.setText("Save");
        menuSave.addActionListener(this::menuSaveActionPerformed);
        jMenu1.add(menuSave);

        menuSaveAs.setText("Save As");
        menuSaveAs.addActionListener(this::menuSaveAsActionPerformed);
        jMenu1.add(menuSaveAs);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        jMenuItem5.setText("Explore");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveAsActionPerformed
        // TODO add your handling code here:
        editorController.saveFileAs();
    }//GEN-LAST:event_menuSaveAsActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
        editorController.saveFile();
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
        // TODO add your handling code here:
        editorController.openFile();
    }//GEN-LAST:event_menuOpenActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane Outer;
    private javax.swing.JScrollPane Side;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem menuOpen;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JMenuItem menuSaveAs;
    private javax.swing.JEditorPane previewPane;
    private javax.swing.JTextArea txtEditor;
    // End of variables declaration//GEN-END:variables
}
